### ISSUE TITLE
Update bulma library

### ISSUE THREAD

**Issue by RDCH106** [anfederico/Flaskex#11]
Very old bulma library. It is very recommendable update at least to 0.6.2 version.

* `nav` tags are [deprecated](https://bulma.io/documentation/components/nav/). Now [`navbar`](https://bulma.io/documentation/components/navbar/) is more powerful option than `nav`
* [Dropdown doesn't support icons](https://github.com/jgthms/bulma/issues/702)

I am going to help you to upgrade bulma library to 0.6.2 version.

**Comment by anfederico** [comment]
Yeah I agree, that'd be awesome if you could help!

**Comment by RDCH106** [comment]
Why did you close this??

It is not solved... Please reopen it and wait until the issue is solved.

Usually the issue is closed with the commit message. You can write `Fix #11` where 11 is the number of the issue and when you merge mi PR (Pull Request) with my changes, the issue will close automatically.
