### ISSUE TITLE
[proposal] code arrangement changes

### ISSUE THREAD

**Issue by newpro** [anfederico/Flaskex#7]
Hey guys!

I looked into the code a little bit recently and want to start adding some more features. But before I do that, I believe the repo need to get some code arrangement changes going on. The reasons are those:
* I want to add some tests before adding features. But without [Application Factories](http://flask.pocoo.org/docs/0.12/patterns/appfactories/) it is hard to write robust test cases.
* I want to add some code that can be disabled and enabled easily by user, but without a setting modules it is also hard to do.
* I believe, but not sure, that manage sqlalchemy session by ourselves is a dangerous, unnecessary, and inconvenience move:
  * dangerous and inconvenience: it is hard to write test cases to validate session has been stored correctly.
  * dangerous: any other features has to manage the sessions by themselves, and it is not easy to get it right.
  * unnecessary: [flask-sqlalchemy](https://github.com/mitsuhiko/flask-sqlalchemy) is a very robust and battle-tested application wrapper for this. Should just use it.

So my proposed changes are:
* flask-sqlalchemy
* application factory
* configuration class implementation

I am hesitate to issue pull request right away to correct those, because I think there might be a reason this repo not using those changes: let beginner easily understand the code. So I want to post this thread here to ask opinions about everyone, and contributors @anfederico @pl77. 

Also forgot to mention, this repo need a universal code style, i can see 15bd6b951b8cde1f4fac30d4a02b5442d65c6eda is trying to convert to pep8, but currently the codebase is not. If pep8 is the intention may i recommend to use [git pep8 hook](https://github.com/cbrueffer/pep8-git-hook) to make sure all future commit is enforced.

Let me know what u think. As always keeps up the good work!

Happy Canada Day!

**Comment by anfederico** [comment]
Thanks for the post, and yes I agree with your analysis. In regard to your proposed changes, I'm on board. Initially the goal was to maximize user friendliness but we also want to encourage good practices. Also, yes, I agree we should make a habit out of the PEP8 hook, good suggestion. Looking forward to working on these changes with you.

**Comment by pl77** [comment]
I agree with anfederico's response.  These are good changes.  Sorry for the delayed response, another repo had resulted in an avalanche of notifications and this one got buried until I was able to delete the rest.

**Comment by newpro** [comment]
great I will start working on those in my spare time and post pull request asap. 

- [ ] session by flasksqlalchemy
- [ ] application factory
- [ ] configuration by class

Cheers!

**Comment by anfederico** [comment]
Will close this as I think we'll stick with the simple example.
